# Generated by Django 6.0.6 on 2026-06-25 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('counterparty', models.CharField(max_length=255, verbose_name='Контрагент')),
                ('contract_type', models.CharField(choices=[('SUPPLY', 'Поставка'), ('SERVICES', 'Услуги'), ('RENT', 'Аренда'), ('NDA', 'NDA'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип договора')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('LAWYER', 'На согласовании у юриста'), ('ACCOUNTANT', 'На согласовании у бухгалтера'), ('SIGNING', 'На подписании'), ('SIGNED', 'Подписан'), ('REJECTED', 'Отклонен')], default='DRAFT', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания')),
                ('responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('DRAFT', 'Черновик'), ('LAWYER', 'На согласовании у юриста'), ('ACCOUNTANT', 'На согласовании у бухгалтера'), ('SIGNING', 'На подписании'), ('SIGNED', 'Подписан'), ('REJECTED', 'Отклонен')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('DRAFT', 'Черновик'), ('LAWYER', 'На согласовании у юриста'), ('ACCOUNTANT', 'На согласовании у бухгалтера'), ('SIGNING', 'На подписании'), ('SIGNED', 'Подписан'), ('REJECTED', 'Отклонен')], max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'История статусов',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_type'], name='idx_contract_type'),
        ),
    ]
